title: Luigi Maria Briglia
description: Personal website of Luigi Maria Briglia, Postdoctoral Researcher at the University of Tuebingen.
email: luigi.briglia@uni-tuebingen.de
url: https://www.luigibriglia.com
